---
title: "About Me"
---

After completing my undergraduate degree, I embarked on an exciting career at Tata Consultancy Services (TCS), where I spent over five years honing my skills in chatbot development, data analysis, and machine learning. At TCS, I had the privilege of leading a talented team of developers, and together, we built innovative chatbots that significantly improved customer support efficiency and user experience.


## What I Do

I specialize in:

- **Building Intelligent Chatbots**: Creating chatbots using platforms like AWS, Azure, Google and AVAAMO, integrating them seamlessly into client systems.
- **Data Analysis and Visualization**: Utilizing tools like Power BI, Tableau, and Python to turn complex data into clear, actionable insights.
- **Machine Learning and AI Development**: Developing machine learning models to solve real-world problems, with a focus on NLP and generative AI technologies.

## My Journey in Data Science and AI

My curiosity and drive for continuous learning led me to pursue a Master’s degree in Data Science at the University of British Columbia. Here, I delved deeper into the realms of machine learning, natural language processing, and AI development. One of my most fulfilling projects was with Rio Tinto Exploration, where I developed a sophisticated data visualization tool and predictive models to identify mining trends.

## Professional Experience

### Lead Developer & Analyst, Tata Consultancy Services (Feb 2022 – July 2023)
- Developed a chatbot in AVAMMO using Python and NodeJS for a client product, supporting users with product documentation, installation, and technical issues.
- Extracted and analyzed data from SQL & chatbot logs, visualizing it using Power BI to help clients improve customer satisfaction.
- Led and trained a team of 4 developers, ensuring efficient project delivery and skill advancement.
- Achieved a 40% reduction in customer-raised issues on the support portal by developing a BOT that independently handled all L1 cases.

### Chatbot Developer, Tata Consultancy Services (July 2020 – Jan 2022)
- Collaborated with the Digital Center of Excellence (CoE) team to develop chatbots across Azure, AWS, and Google platforms using Python.
- Developed a universal bot that streamlined three different bots, significantly improving cost efficiency for infrastructure maintenance.
- Received the Best Employee of the Year award for the development of the universal bot.

### Lead AWS Developer, Tata Consultancy Services (Jan 2019 – June 2020)
- Managed business requirements, bot design, conversation analysis, and stakeholder reporting while supporting the team in coding and problem-solving.
- Developed conversation flows for chatbots using Python, integrated with AWS services, and implemented CI/CD pipelines with Jenkins and AWS CodePipeline.

### Application Administrator, Tata Consultancy Services (July 2018 – Dec 2018)
- Acquired the ability to translate business requirements into precise technical specifications, while also proficiently analyzing data using SQL, VBA, and Excel/Pivot tables for effective visualization.
- Managed server upgrades, tool licensing, and delivered projects with effective stakeholder communication.

## Capstone Project

### Data Scientist, Rio Tinto Exploration (Vancouver)
- Developed a framework and DASH application to wrangle data and extract drilling trends over a period of 10 years globally, providing intuitive visualization.
- Built a spatial-temporal trend prediction model to identify patterns in mining locations using a multi-output supervised learning model.

## Achievements and Skills

Throughout my career, I've been recognized for my technical acumen and leadership abilities. Some highlights include:

- Leading the development of a chatbot that reduced customer support queries by 40%.
- Receiving the Best Employee of the Year award for developing a universal bot that streamlined multiple systems, enhancing efficiency.
- Earning the Academic Excellence Award during my undergraduate studies.

